version: "2.4.0"

services:

    shopware:
      # use either tag "latest" or any other version like "6.1.5", ...
      build: .docker/.
      container_name: shopware
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
      volumes:
         - "db_volume:/var/lib/mysql"
         - "shop_volume:/var/www/html"
         - "./.docker/mollie.sh:/mollie.sh"
      networks:
         - web
         - traefik-publik
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${NAME_SERVICE}.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${NAME_SERVICE}.entrypoints=web"
        - "traefik.http.services.${NAME_SERVICE}.loadbalancer.server.port=80"
      environment:
        PHP_VERSION: ${PHP_VERSION}
        APACHE_DOCROOT: ${APACHE_DOCROOT}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PWD: ${MYSQL_PWD}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        SW_CURRENCY: ${SW_CURRENCY}
        SW_API_ACCESS_KEY: ${SW_API_ACCESS_KEY}
        SW_TASKS_ENABLED: ${SW_TASKS_ENABLED}
        MOLLIE_VERSION: ${MOLLIE_VERSION}
        DOMAIN: ${DOMAIN}


volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
    traefik-public:
        name: traefik-public